server:
  port: 8888


spring:
  datasource:
    # 数据源
    url: jdbc:mysql://120.77.213.159:3307/wiki?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime:  500000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#  rabbitmq:
#      host: 127.0.0.1
#      port: 5672


#  redis:
#    host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
#    port: 6379
#    password: Redis000

  redis:
    host: 120.77.213.159
    port: 6379
    password:


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
# 打印所有的sql日志：sql, 参数, 结果


logging:
  level:
    com.wiki.spring.mapper: trace




